### ISSUE TITLE
Please remove an image

### ISSUE THREAD

**Issue by Shirisu** [bangnomo/cloud-gallery-fe#1]
Hi - I wanted to test something with your demo and uploaded a wrong image..
Could you please remove it from your demo space?
It's this image: https://res.cloudinary.com/bangdigi/image/upload/v1657112553/dog_pictures/y2cf6yghsqvfbb8orc0r.jpg 

Thank you!!

**Comment by bangnomo** [comment]
I removed it. I almost forgot that site.
Kind regards.

Vào 20:08, Th 4, 6 thg 7, 2022 San ***@***.***> đã viết:

**Comment by Shirisu** [comment]
Thank you and you're welcome! 😄
